package com.yuantu.dao.finance;

import com.yuantu.entity.finance.MeslAccountUpdate;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MeslAccountUpdateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_account_update
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    int insert(MeslAccountUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_account_update
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    int insertSelective(MeslAccountUpdate record);

    void insertAccount(MeslAccountUpdate meslAccountUpdate);

    void updateAccount(MeslAccountUpdate meslAccountUpdate);

    MeslAccountUpdate selectUpdateAccount();
}