package com.yuantu.dao.tcsalesman;

import com.yuantu.entity.tcsalesman.MeslReceive;

import java.util.List;

public interface MeslReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_receive
     *
     * @mbggenerated Tue Jul 30 16:00:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_receive
     *
     * @mbggenerated Tue Jul 30 16:00:09 CST 2019
     */
    int insert(MeslReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_receive
     *
     * @mbggenerated Tue Jul 30 16:00:09 CST 2019
     */
    int insertSelective(MeslReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_receive
     *
     * @mbggenerated Tue Jul 30 16:00:09 CST 2019
     */
    MeslReceive selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_receive
     *
     * @mbggenerated Tue Jul 30 16:00:09 CST 2019
     */
    int updateByPrimaryKeySelective(MeslReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_receive
     *
     * @mbggenerated Tue Jul 30 16:00:09 CST 2019
     */
    int updateByPrimaryKey(MeslReceive record);

    MeslReceive insertReceive(MeslReceive meslReceive);

    MeslReceive updateReceive(MeslReceive meslReceive);

    List<MeslReceive> selectReceive();

    MeslReceive selectReceiveByExpressorderNumber(String expressorderNumber);
}