package com.yuantu.dao.tcsalesman;

import com.yuantu.entity.tcsalesman.MeslTransportForm;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

public interface MeslTransportFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_transport_form
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_transport_form
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int insert(MeslTransportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_transport_form
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int insertSelective(MeslTransportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_transport_form
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    MeslTransportForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_transport_form
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int updateByPrimaryKeySelective(MeslTransportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_transport_form
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int updateByPrimaryKey(MeslTransportForm record);

    void insertTransportForm(@Param("transportNumber") String transportNumber, @Param("expressorderNumber") String expressorderNumber);

    List<MeslTransportForm> selectTransportForm();

    MeslTransportForm selectTransportFormByExpressorderNumber(String expressorderNumber);
}