package com.yuantu.dao.tcsalesman;

import com.yuantu.entity.tcsalesman.MeslShipping;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MeslShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_shipping
     *
     * @mbggenerated Tue Jul 16 13:45:48 CST 2019
     */
    int insert(MeslShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_shipping
     *
     * @mbggenerated Tue Jul 16 13:45:48 CST 2019
     */
    int insertSelective(MeslShipping record);
    MeslShipping insertShipping(MeslShipping meslShipping);
    void updateShippingorderNumber(String shippingorderNumber,Integer id);
    void updateShippingTime(String shippingTime,Integer id);
    void updateTrainNumber(String trainNumber,Integer id);
    void updateOrigin(String origin,Integer id);
    void updateDestination(String destination,Integer id);
    void updateCarriageNumber(String carriageNumber,Integer id);
    void updateOperator(String operator,Integer id);
    List<MeslShipping> selectShipping();
}