package com.yuantu.dao.tcsalesman;

import com.yuantu.entity.tcsalesman.MeslReceive;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MeslReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_receive
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    int insert(MeslReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_receive
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    int insertSelective(MeslReceive record);

    MeslReceive insertReceive(String receiveNumber, String receiveTime, String origin, String receivePlace, String freightBatchNumber, String freight);
}