package com.yuantu.dao.tcsalesman;

import com.yuantu.entity.tcsalesman.MeslShipping;

import java.util.List;

public interface MeslShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_shipping
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_shipping
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    int insert(MeslShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_shipping
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    int insertSelective(MeslShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_shipping
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    MeslShipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_shipping
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    int updateByPrimaryKeySelective(MeslShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_shipping
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    int updateByPrimaryKey(MeslShipping record);

    MeslShipping insertShipping(MeslShipping meslShipping);

    MeslShipping updateShipping(MeslShipping meslShipping);

    List<MeslShipping> selectShipping();

    MeslShipping selectShippingByNum(String expressorderNumber);
}