package com.yuantu.dao.tcsalesman;

import com.yuantu.entity.tcsalesman.MeslLogistics;

public interface MeslLogisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_logistics
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    int insert(MeslLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_logistics
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    int insertSelective(MeslLogistics record);
}