package com.yuantu.dao.tcsalesman;

import com.yuantu.entity.tcsalesman.MeslLogistics;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MeslLogisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_logistics
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_logistics
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int insert(MeslLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_logistics
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int insertSelective(MeslLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_logistics
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    MeslLogistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_logistics
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int updateByPrimaryKeySelective(MeslLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_logistics
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    int updateByPrimaryKey(MeslLogistics record);

    void insertLogistics(MeslLogistics meslLogistics);

    void updateLogisticsNum(@Param("logisticsNumber") String logisticsNumber, @Param("id") Integer id);

    MeslLogistics selectLogisticsByLogisticsNumber(String logisticsNumber);
}