package com.yuantu.entity.tcsalesman;

public class MeslShipping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.id
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.shippingorder_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String shippingorderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.expressorder_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String expressorderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.shipping_time
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String shippingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.train_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String trainNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.origin
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.destination
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.carriage_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String carriageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.operator
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_shipping.freight
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    private String freight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.id
     *
     * @return the value of mesl_shipping.id
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.id
     *
     * @param id the value for mesl_shipping.id
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.shippingorder_number
     *
     * @return the value of mesl_shipping.shippingorder_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getShippingorderNumber() {
        return shippingorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.shippingorder_number
     *
     * @param shippingorderNumber the value for mesl_shipping.shippingorder_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setShippingorderNumber(String shippingorderNumber) {
        this.shippingorderNumber = shippingorderNumber == null ? null : shippingorderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.expressorder_number
     *
     * @return the value of mesl_shipping.expressorder_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getExpressorderNumber() {
        return expressorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.expressorder_number
     *
     * @param expressorderNumber the value for mesl_shipping.expressorder_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setExpressorderNumber(String expressorderNumber) {
        this.expressorderNumber = expressorderNumber == null ? null : expressorderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.shipping_time
     *
     * @return the value of mesl_shipping.shipping_time
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getShippingTime() {
        return shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.shipping_time
     *
     * @param shippingTime the value for mesl_shipping.shipping_time
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setShippingTime(String shippingTime) {
        this.shippingTime = shippingTime == null ? null : shippingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.train_number
     *
     * @return the value of mesl_shipping.train_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getTrainNumber() {
        return trainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.train_number
     *
     * @param trainNumber the value for mesl_shipping.train_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setTrainNumber(String trainNumber) {
        this.trainNumber = trainNumber == null ? null : trainNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.origin
     *
     * @return the value of mesl_shipping.origin
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.origin
     *
     * @param origin the value for mesl_shipping.origin
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.destination
     *
     * @return the value of mesl_shipping.destination
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.destination
     *
     * @param destination the value for mesl_shipping.destination
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.carriage_number
     *
     * @return the value of mesl_shipping.carriage_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getCarriageNumber() {
        return carriageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.carriage_number
     *
     * @param carriageNumber the value for mesl_shipping.carriage_number
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setCarriageNumber(String carriageNumber) {
        this.carriageNumber = carriageNumber == null ? null : carriageNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.operator
     *
     * @return the value of mesl_shipping.operator
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.operator
     *
     * @param operator the value for mesl_shipping.operator
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_shipping.freight
     *
     * @return the value of mesl_shipping.freight
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public String getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_shipping.freight
     *
     * @param freight the value for mesl_shipping.freight
     *
     * @mbggenerated Tue Jul 30 16:58:22 CST 2019
     */
    public void setFreight(String freight) {
        this.freight = freight == null ? null : freight.trim();
    }
}