package com.yuantu.entity.tcsalesman;

public class MeslReceive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receive.id
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receive.receive_number
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String receiveNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receive.receive_time
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String receiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receive.origin
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receive.receive_place
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String receivePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receive.freight_batch_number
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String freightBatchNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receive.freight
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String freight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receive.id
     *
     * @return the value of mesl_receive.id
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receive.id
     *
     * @param id the value for mesl_receive.id
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receive.receive_number
     *
     * @return the value of mesl_receive.receive_number
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getReceiveNumber() {
        return receiveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receive.receive_number
     *
     * @param receiveNumber the value for mesl_receive.receive_number
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setReceiveNumber(String receiveNumber) {
        this.receiveNumber = receiveNumber == null ? null : receiveNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receive.receive_time
     *
     * @return the value of mesl_receive.receive_time
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receive.receive_time
     *
     * @param receiveTime the value for mesl_receive.receive_time
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setReceiveTime(String receiveTime) {
        this.receiveTime = receiveTime == null ? null : receiveTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receive.origin
     *
     * @return the value of mesl_receive.origin
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receive.origin
     *
     * @param origin the value for mesl_receive.origin
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receive.receive_place
     *
     * @return the value of mesl_receive.receive_place
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getReceivePlace() {
        return receivePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receive.receive_place
     *
     * @param receivePlace the value for mesl_receive.receive_place
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setReceivePlace(String receivePlace) {
        this.receivePlace = receivePlace == null ? null : receivePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receive.freight_batch_number
     *
     * @return the value of mesl_receive.freight_batch_number
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getFreightBatchNumber() {
        return freightBatchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receive.freight_batch_number
     *
     * @param freightBatchNumber the value for mesl_receive.freight_batch_number
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setFreightBatchNumber(String freightBatchNumber) {
        this.freightBatchNumber = freightBatchNumber == null ? null : freightBatchNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receive.freight
     *
     * @return the value of mesl_receive.freight
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receive.freight
     *
     * @param freight the value for mesl_receive.freight
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setFreight(String freight) {
        this.freight = freight == null ? null : freight.trim();
    }
}