package com.yuantu.entity.tcsalesman;

public class MeslLogistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.id
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.expressorder_number
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String expressorderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.operation
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.operation_people
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String operationPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.origin
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.destination
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.date
     *
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.id
     *
     * @return the value of mesl_logistics.id
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.id
     *
     * @param id the value for mesl_logistics.id
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.expressorder_number
     *
     * @return the value of mesl_logistics.expressorder_number
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getExpressorderNumber() {
        return expressorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.expressorder_number
     *
     * @param expressorderNumber the value for mesl_logistics.expressorder_number
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setExpressorderNumber(String expressorderNumber) {
        this.expressorderNumber = expressorderNumber == null ? null : expressorderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.operation
     *
     * @return the value of mesl_logistics.operation
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.operation
     *
     * @param operation the value for mesl_logistics.operation
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.operation_people
     *
     * @return the value of mesl_logistics.operation_people
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getOperationPeople() {
        return operationPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.operation_people
     *
     * @param operationPeople the value for mesl_logistics.operation_people
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setOperationPeople(String operationPeople) {
        this.operationPeople = operationPeople == null ? null : operationPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.origin
     *
     * @return the value of mesl_logistics.origin
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.origin
     *
     * @param origin the value for mesl_logistics.origin
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.destination
     *
     * @return the value of mesl_logistics.destination
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.destination
     *
     * @param destination the value for mesl_logistics.destination
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.date
     *
     * @return the value of mesl_logistics.date
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.date
     *
     * @param date the value for mesl_logistics.date
     * @mbggenerated Fri Jun 28 14:34:58 CST 2019
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}