package com.yuantu.entity.tcsalesman;

public class MeslLogistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.id
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.logistics_number
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    private String logisticsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.historical
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    private String historical;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_logistics.transport_number
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    private String transportNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.id
     *
     * @return the value of mesl_logistics.id
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.id
     *
     * @param id the value for mesl_logistics.id
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.logistics_number
     *
     * @return the value of mesl_logistics.logistics_number
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    public String getLogisticsNumber() {
        return logisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.logistics_number
     *
     * @param logisticsNumber the value for mesl_logistics.logistics_number
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    public void setLogisticsNumber(String logisticsNumber) {
        this.logisticsNumber = logisticsNumber == null ? null : logisticsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.historical
     *
     * @return the value of mesl_logistics.historical
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    public String getHistorical() {
        return historical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.historical
     *
     * @param historical the value for mesl_logistics.historical
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    public void setHistorical(String historical) {
        this.historical = historical == null ? null : historical.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_logistics.transport_number
     *
     * @return the value of mesl_logistics.transport_number
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    public String getTransportNumber() {
        return transportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_logistics.transport_number
     *
     * @param transportNumber the value for mesl_logistics.transport_number
     *
     * @mbggenerated Tue Jul 30 13:33:53 CST 2019
     */
    public void setTransportNumber(String transportNumber) {
        this.transportNumber = transportNumber == null ? null : transportNumber.trim();
    }
}