package com.yuantu.dao.tcstoreman;

import com.yuantu.entity.tcstoreman.MeslIntoStorehouse;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface MeslIntoStorehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_into_storehouse
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    int insert(MeslIntoStorehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_into_storehouse
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    int insertSelective(MeslIntoStorehouse record);

    void insertStore(MeslIntoStorehouse meslIntoStorehouse);

    List<MeslIntoStorehouse> selectStorehouse();

    MeslIntoStorehouse selectStorehouseByDate(@Param("startDate") Date startDate, @Param("endDate") Date endDate);

    MeslIntoStorehouse selectStorehouseByExpressorderNumber(String expressorderNumber);
}