package com.yuantu.dao.tcstoreman;

import com.yuantu.entity.tcstoreman.MeslStock;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MeslStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_stock
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    int insert(MeslStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_stock
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    int insertSelective(MeslStock record);

    void insertStock(MeslStock meslStock);

    List<MeslStock> selectStock(String state);

    void updateState(@Param("state") String state, @Param("id") String id);

    long selectCount(String state);
}