package com.yuantu.entity.courier;

public class MeslMail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.id
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.expressorder_number
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String expressorderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.sender_name
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String senderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.sender_phone
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String senderPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.sender_address
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String senderAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.recipient_name
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String recipientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.recipient_phone
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String recipientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.recipient_address
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String recipientAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.cargo_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String cargoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.cargo_weight
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String cargoWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.cargo_size
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String cargoSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.pack_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String packType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.transport_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String transportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.appointment_time
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String appointmentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.mail_state
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String mailState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_mail.mail_logistics
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    private String mailLogistics;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.id
     *
     * @return the value of mesl_mail.id
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.id
     *
     * @param id the value for mesl_mail.id
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.expressorder_number
     *
     * @return the value of mesl_mail.expressorder_number
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getExpressorderNumber() {
        return expressorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.expressorder_number
     *
     * @param expressorderNumber the value for mesl_mail.expressorder_number
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setExpressorderNumber(String expressorderNumber) {
        this.expressorderNumber = expressorderNumber == null ? null : expressorderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.sender_name
     *
     * @return the value of mesl_mail.sender_name
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.sender_name
     *
     * @param senderName the value for mesl_mail.sender_name
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.sender_phone
     *
     * @return the value of mesl_mail.sender_phone
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getSenderPhone() {
        return senderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.sender_phone
     *
     * @param senderPhone the value for mesl_mail.sender_phone
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setSenderPhone(String senderPhone) {
        this.senderPhone = senderPhone == null ? null : senderPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.sender_address
     *
     * @return the value of mesl_mail.sender_address
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.sender_address
     *
     * @param senderAddress the value for mesl_mail.sender_address
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress == null ? null : senderAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.recipient_name
     *
     * @return the value of mesl_mail.recipient_name
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.recipient_name
     *
     * @param recipientName the value for mesl_mail.recipient_name
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName == null ? null : recipientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.recipient_phone
     *
     * @return the value of mesl_mail.recipient_phone
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getRecipientPhone() {
        return recipientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.recipient_phone
     *
     * @param recipientPhone the value for mesl_mail.recipient_phone
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setRecipientPhone(String recipientPhone) {
        this.recipientPhone = recipientPhone == null ? null : recipientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.recipient_address
     *
     * @return the value of mesl_mail.recipient_address
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getRecipientAddress() {
        return recipientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.recipient_address
     *
     * @param recipientAddress the value for mesl_mail.recipient_address
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setRecipientAddress(String recipientAddress) {
        this.recipientAddress = recipientAddress == null ? null : recipientAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.cargo_type
     *
     * @return the value of mesl_mail.cargo_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getCargoType() {
        return cargoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.cargo_type
     *
     * @param cargoType the value for mesl_mail.cargo_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setCargoType(String cargoType) {
        this.cargoType = cargoType == null ? null : cargoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.cargo_weight
     *
     * @return the value of mesl_mail.cargo_weight
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getCargoWeight() {
        return cargoWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.cargo_weight
     *
     * @param cargoWeight the value for mesl_mail.cargo_weight
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setCargoWeight(String cargoWeight) {
        this.cargoWeight = cargoWeight == null ? null : cargoWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.cargo_size
     *
     * @return the value of mesl_mail.cargo_size
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getCargoSize() {
        return cargoSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.cargo_size
     *
     * @param cargoSize the value for mesl_mail.cargo_size
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setCargoSize(String cargoSize) {
        this.cargoSize = cargoSize == null ? null : cargoSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.pack_type
     *
     * @return the value of mesl_mail.pack_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getPackType() {
        return packType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.pack_type
     *
     * @param packType the value for mesl_mail.pack_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setPackType(String packType) {
        this.packType = packType == null ? null : packType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.transport_type
     *
     * @return the value of mesl_mail.transport_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getTransportType() {
        return transportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.transport_type
     *
     * @param transportType the value for mesl_mail.transport_type
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setTransportType(String transportType) {
        this.transportType = transportType == null ? null : transportType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.appointment_time
     *
     * @return the value of mesl_mail.appointment_time
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getAppointmentTime() {
        return appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.appointment_time
     *
     * @param appointmentTime the value for mesl_mail.appointment_time
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setAppointmentTime(String appointmentTime) {
        this.appointmentTime = appointmentTime == null ? null : appointmentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.mail_state
     *
     * @return the value of mesl_mail.mail_state
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getMailState() {
        return mailState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.mail_state
     *
     * @param mailState the value for mesl_mail.mail_state
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setMailState(String mailState) {
        this.mailState = mailState == null ? null : mailState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_mail.mail_logistics
     *
     * @return the value of mesl_mail.mail_logistics
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public String getMailLogistics() {
        return mailLogistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_mail.mail_logistics
     *
     * @param mailLogistics the value for mesl_mail.mail_logistics
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    public void setMailLogistics(String mailLogistics) {
        this.mailLogistics = mailLogistics == null ? null : mailLogistics.trim();
    }
}