package com.yuantu.entity.finance;

import java.util.Date;

public class MeslCostProfit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_cost_profit.id
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_cost_profit.cost_profit__date
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    private Date costProfitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_cost_profit.dept_number
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    private String deptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_cost_profit.total_expend
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    private String totalExpend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_cost_profit.total_income
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    private String totalIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_cost_profit.total_profit
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    private String totalProfit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_cost_profit.id
     *
     * @return the value of mesl_cost_profit.id
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_cost_profit.id
     *
     * @param id the value for mesl_cost_profit.id
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_cost_profit.cost_profit__date
     *
     * @return the value of mesl_cost_profit.cost_profit__date
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public Date getCostProfitDate() {
        return costProfitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_cost_profit.cost_profit__date
     *
     * @param costProfitDate the value for mesl_cost_profit.cost_profit__date
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public void setCostProfitDate(Date costProfitDate) {
        this.costProfitDate = costProfitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_cost_profit.dept_number
     *
     * @return the value of mesl_cost_profit.dept_number
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public String getDeptNumber() {
        return deptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_cost_profit.dept_number
     *
     * @param deptNumber the value for mesl_cost_profit.dept_number
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public void setDeptNumber(String deptNumber) {
        this.deptNumber = deptNumber == null ? null : deptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_cost_profit.total_expend
     *
     * @return the value of mesl_cost_profit.total_expend
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public String getTotalExpend() {
        return totalExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_cost_profit.total_expend
     *
     * @param totalExpend the value for mesl_cost_profit.total_expend
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public void setTotalExpend(String totalExpend) {
        this.totalExpend = totalExpend == null ? null : totalExpend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_cost_profit.total_income
     *
     * @return the value of mesl_cost_profit.total_income
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public String getTotalIncome() {
        return totalIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_cost_profit.total_income
     *
     * @param totalIncome the value for mesl_cost_profit.total_income
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public void setTotalIncome(String totalIncome) {
        this.totalIncome = totalIncome == null ? null : totalIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_cost_profit.total_profit
     *
     * @return the value of mesl_cost_profit.total_profit
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public String getTotalProfit() {
        return totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_cost_profit.total_profit
     *
     * @param totalProfit the value for mesl_cost_profit.total_profit
     *
     * @mbggenerated Fri Jun 28 16:00:13 CST 2019
     */
    public void setTotalProfit(String totalProfit) {
        this.totalProfit = totalProfit == null ? null : totalProfit.trim();
    }
}