package com.yuantu.entity.finance;

public class MeslPayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_payment.id
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_payment.payment_number
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    private String paymentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_payment.payment_type
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_payment.payment_date
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    private String paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_payment.payment_person
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    private String paymentPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_payment.payment_money
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    private String paymentMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_payment.payment_account
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    private String paymentAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_payment.id
     *
     * @return the value of mesl_payment.id
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_payment.id
     *
     * @param id the value for mesl_payment.id
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_payment.payment_number
     *
     * @return the value of mesl_payment.payment_number
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public String getPaymentNumber() {
        return paymentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_payment.payment_number
     *
     * @param paymentNumber the value for mesl_payment.payment_number
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public void setPaymentNumber(String paymentNumber) {
        this.paymentNumber = paymentNumber == null ? null : paymentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_payment.payment_type
     *
     * @return the value of mesl_payment.payment_type
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_payment.payment_type
     *
     * @param paymentType the value for mesl_payment.payment_type
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_payment.payment_date
     *
     * @return the value of mesl_payment.payment_date
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_payment.payment_date
     *
     * @param paymentDate the value for mesl_payment.payment_date
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate == null ? null : paymentDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_payment.payment_person
     *
     * @return the value of mesl_payment.payment_person
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public String getPaymentPerson() {
        return paymentPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_payment.payment_person
     *
     * @param paymentPerson the value for mesl_payment.payment_person
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public void setPaymentPerson(String paymentPerson) {
        this.paymentPerson = paymentPerson == null ? null : paymentPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_payment.payment_money
     *
     * @return the value of mesl_payment.payment_money
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public String getPaymentMoney() {
        return paymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_payment.payment_money
     *
     * @param paymentMoney the value for mesl_payment.payment_money
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public void setPaymentMoney(String paymentMoney) {
        this.paymentMoney = paymentMoney == null ? null : paymentMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_payment.payment_account
     *
     * @return the value of mesl_payment.payment_account
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public String getPaymentAccount() {
        return paymentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_payment.payment_account
     *
     * @param paymentAccount the value for mesl_payment.payment_account
     *
     * @mbggenerated Thu Jun 27 18:20:00 CST 2019
     */
    public void setPaymentAccount(String paymentAccount) {
        this.paymentAccount = paymentAccount == null ? null : paymentAccount.trim();
    }
}