package com.yuantu.entity.finance;

public class MeslReceipt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receipt.id
     *
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receipt.receiptorder_number
     *
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    private String receiptorderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receipt.expressorder_number
     *
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    private String expressorderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receipt.receipt_time
     *
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    private String receiptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receipt.staff_number
     *
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    private String staffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receipt.postage
     *
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    private String postage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receipt.packaging_expense
     *
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    private String packagingExpense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_receipt.actual_receipt_money
     *
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    private String actualReceiptMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receipt.id
     *
     * @return the value of mesl_receipt.id
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receipt.id
     *
     * @param id the value for mesl_receipt.id
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receipt.receiptorder_number
     *
     * @return the value of mesl_receipt.receiptorder_number
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public String getReceiptorderNumber() {
        return receiptorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receipt.receiptorder_number
     *
     * @param receiptorderNumber the value for mesl_receipt.receiptorder_number
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public void setReceiptorderNumber(String receiptorderNumber) {
        this.receiptorderNumber = receiptorderNumber == null ? null : receiptorderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receipt.expressorder_number
     *
     * @return the value of mesl_receipt.expressorder_number
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public String getExpressorderNumber() {
        return expressorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receipt.expressorder_number
     *
     * @param expressorderNumber the value for mesl_receipt.expressorder_number
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public void setExpressorderNumber(String expressorderNumber) {
        this.expressorderNumber = expressorderNumber == null ? null : expressorderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receipt.receipt_time
     *
     * @return the value of mesl_receipt.receipt_time
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public String getReceiptTime() {
        return receiptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receipt.receipt_time
     *
     * @param receiptTime the value for mesl_receipt.receipt_time
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public void setReceiptTime(String receiptTime) {
        this.receiptTime = receiptTime == null ? null : receiptTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receipt.staff_number
     *
     * @return the value of mesl_receipt.staff_number
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public String getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receipt.staff_number
     *
     * @param staffNumber the value for mesl_receipt.staff_number
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber == null ? null : staffNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receipt.postage
     *
     * @return the value of mesl_receipt.postage
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public String getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receipt.postage
     *
     * @param postage the value for mesl_receipt.postage
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public void setPostage(String postage) {
        this.postage = postage == null ? null : postage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receipt.packaging_expense
     *
     * @return the value of mesl_receipt.packaging_expense
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public String getPackagingExpense() {
        return packagingExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receipt.packaging_expense
     *
     * @param packagingExpense the value for mesl_receipt.packaging_expense
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public void setPackagingExpense(String packagingExpense) {
        this.packagingExpense = packagingExpense == null ? null : packagingExpense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_receipt.actual_receipt_money
     *
     * @return the value of mesl_receipt.actual_receipt_money
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public String getActualReceiptMoney() {
        return actualReceiptMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_receipt.actual_receipt_money
     *
     * @param actualReceiptMoney the value for mesl_receipt.actual_receipt_money
     * @mbggenerated Wed Jul 10 16:15:15 CST 2019
     */
    public void setActualReceiptMoney(String actualReceiptMoney) {
        this.actualReceiptMoney = actualReceiptMoney == null ? null : actualReceiptMoney.trim();
    }
}