package com.yuantu.entity.finance;

public class MeslAccountUpdate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_account_update.id
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_account_update.update_dept
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    private String updateDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_account_update.update_personnel
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    private String updatePersonnel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_account_update.update_trucks
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    private String updateTrucks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_account_update.update_stock
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    private String updateStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_account_update.update_account_name
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    private String updateAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_account_update.update_account_money
     *
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    private String updateAccountMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_account_update.id
     *
     * @return the value of mesl_account_update.id
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_account_update.id
     *
     * @param id the value for mesl_account_update.id
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_account_update.update_dept
     *
     * @return the value of mesl_account_update.update_dept
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public String getUpdateDept() {
        return updateDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_account_update.update_dept
     *
     * @param updateDept the value for mesl_account_update.update_dept
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public void setUpdateDept(String updateDept) {
        this.updateDept = updateDept == null ? null : updateDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_account_update.update_personnel
     *
     * @return the value of mesl_account_update.update_personnel
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public String getUpdatePersonnel() {
        return updatePersonnel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_account_update.update_personnel
     *
     * @param updatePersonnel the value for mesl_account_update.update_personnel
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public void setUpdatePersonnel(String updatePersonnel) {
        this.updatePersonnel = updatePersonnel == null ? null : updatePersonnel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_account_update.update_trucks
     *
     * @return the value of mesl_account_update.update_trucks
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public String getUpdateTrucks() {
        return updateTrucks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_account_update.update_trucks
     *
     * @param updateTrucks the value for mesl_account_update.update_trucks
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public void setUpdateTrucks(String updateTrucks) {
        this.updateTrucks = updateTrucks == null ? null : updateTrucks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_account_update.update_stock
     *
     * @return the value of mesl_account_update.update_stock
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public String getUpdateStock() {
        return updateStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_account_update.update_stock
     *
     * @param updateStock the value for mesl_account_update.update_stock
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public void setUpdateStock(String updateStock) {
        this.updateStock = updateStock == null ? null : updateStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_account_update.update_account_name
     *
     * @return the value of mesl_account_update.update_account_name
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public String getUpdateAccountName() {
        return updateAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_account_update.update_account_name
     *
     * @param updateAccountName the value for mesl_account_update.update_account_name
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public void setUpdateAccountName(String updateAccountName) {
        this.updateAccountName = updateAccountName == null ? null : updateAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_account_update.update_account_money
     *
     * @return the value of mesl_account_update.update_account_money
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public String getUpdateAccountMoney() {
        return updateAccountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_account_update.update_account_money
     *
     * @param updateAccountMoney the value for mesl_account_update.update_account_money
     * @mbggenerated Wed Jul 10 15:02:32 CST 2019
     */
    public void setUpdateAccountMoney(String updateAccountMoney) {
        this.updateAccountMoney = updateAccountMoney == null ? null : updateAccountMoney.trim();
    }
}