package com.yuantu.dao.courier;

import com.yuantu.entity.courier.MeslMail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MeslMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_mail
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    int insert(MeslMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mesl_mail
     *
     * @mbggenerated Thu Jul 25 17:43:38 CST 2019
     */
    int insertSelective(MeslMail record);
    void updateMail(MeslMail meslMail);
    List<MeslMail> selectMailByState(@Param("state") String state,@Param("recipientAddress")String recipientAddress);
    void updateState(String state);
}