package com.yuantu.entity.tcstoreman;

public class MeslStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_stock.id
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_stock.expressorder_number
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String expressorderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_stock.area_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_stock.row_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String rowCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_stock.shelves_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String shelvesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_stock.seat_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String seatCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_stock.stock_state
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String stockState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_stock.id
     *
     * @return the value of mesl_stock.id
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_stock.id
     *
     * @param id the value for mesl_stock.id
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_stock.expressorder_number
     *
     * @return the value of mesl_stock.expressorder_number
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getExpressorderNumber() {
        return expressorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_stock.expressorder_number
     *
     * @param expressorderNumber the value for mesl_stock.expressorder_number
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setExpressorderNumber(String expressorderNumber) {
        this.expressorderNumber = expressorderNumber == null ? null : expressorderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_stock.area_code
     *
     * @return the value of mesl_stock.area_code
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_stock.area_code
     *
     * @param areaCode the value for mesl_stock.area_code
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_stock.row_code
     *
     * @return the value of mesl_stock.row_code
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getRowCode() {
        return rowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_stock.row_code
     *
     * @param rowCode the value for mesl_stock.row_code
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setRowCode(String rowCode) {
        this.rowCode = rowCode == null ? null : rowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_stock.shelves_code
     *
     * @return the value of mesl_stock.shelves_code
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getShelvesCode() {
        return shelvesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_stock.shelves_code
     *
     * @param shelvesCode the value for mesl_stock.shelves_code
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setShelvesCode(String shelvesCode) {
        this.shelvesCode = shelvesCode == null ? null : shelvesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_stock.seat_code
     *
     * @return the value of mesl_stock.seat_code
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getSeatCode() {
        return seatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_stock.seat_code
     *
     * @param seatCode the value for mesl_stock.seat_code
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setSeatCode(String seatCode) {
        this.seatCode = seatCode == null ? null : seatCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_stock.stock_state
     *
     * @return the value of mesl_stock.stock_state
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getStockState() {
        return stockState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_stock.stock_state
     *
     * @param stockState the value for mesl_stock.stock_state
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setStockState(String stockState) {
        this.stockState = stockState == null ? null : stockState.trim();
    }
}