package com.yuantu.entity.tcstoreman;

import java.util.Date;

public class MeslIntoStorehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_into_storehouse.id
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_into_storehouse.expressorder_number
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String expressorderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_into_storehouse.into_storehouse_date
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private Date intoStorehouseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_into_storehouse.destination
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_into_storehouse.area_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_into_storehouse.row_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String rowCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_into_storehouse.shelves_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String shelvesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mesl_into_storehouse.seat_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    private String seatCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_into_storehouse.id
     *
     * @return the value of mesl_into_storehouse.id
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_into_storehouse.id
     *
     * @param id the value for mesl_into_storehouse.id
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_into_storehouse.expressorder_number
     *
     * @return the value of mesl_into_storehouse.expressorder_number
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getExpressorderNumber() {
        return expressorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_into_storehouse.expressorder_number
     *
     * @param expressorderNumber the value for mesl_into_storehouse.expressorder_number
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setExpressorderNumber(String expressorderNumber) {
        this.expressorderNumber = expressorderNumber == null ? null : expressorderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_into_storehouse.into_storehouse_date
     *
     * @return the value of mesl_into_storehouse.into_storehouse_date
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public Date getIntoStorehouseDate() {
        return intoStorehouseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_into_storehouse.into_storehouse_date
     *
     * @param intoStorehouseDate the value for mesl_into_storehouse.into_storehouse_date
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setIntoStorehouseDate(Date intoStorehouseDate) {
        this.intoStorehouseDate = intoStorehouseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_into_storehouse.destination
     *
     * @return the value of mesl_into_storehouse.destination
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_into_storehouse.destination
     *
     * @param destination the value for mesl_into_storehouse.destination
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_into_storehouse.area_code
     *
     * @return the value of mesl_into_storehouse.area_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_into_storehouse.area_code
     *
     * @param areaCode the value for mesl_into_storehouse.area_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_into_storehouse.row_code
     *
     * @return the value of mesl_into_storehouse.row_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getRowCode() {
        return rowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_into_storehouse.row_code
     *
     * @param rowCode the value for mesl_into_storehouse.row_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setRowCode(String rowCode) {
        this.rowCode = rowCode == null ? null : rowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_into_storehouse.shelves_code
     *
     * @return the value of mesl_into_storehouse.shelves_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getShelvesCode() {
        return shelvesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_into_storehouse.shelves_code
     *
     * @param shelvesCode the value for mesl_into_storehouse.shelves_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setShelvesCode(String shelvesCode) {
        this.shelvesCode = shelvesCode == null ? null : shelvesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mesl_into_storehouse.seat_code
     *
     * @return the value of mesl_into_storehouse.seat_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public String getSeatCode() {
        return seatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mesl_into_storehouse.seat_code
     *
     * @param seatCode the value for mesl_into_storehouse.seat_code
     *
     * @mbggenerated Fri Jun 28 14:39:38 CST 2019
     */
    public void setSeatCode(String seatCode) {
        this.seatCode = seatCode == null ? null : seatCode.trim();
    }
}